#!/bin/sh

CFG_DIR="/etc/config/nftset_configs"
NFT_TABLE="fw4"              # 使用 fw4 的表（与 OpenWrt 防火墙集成）
NFT_PREFIX="myset"           # 集合名称前缀，避免冲突

# ── 初始化 ──────────────────────────────────────────────
init_nftsets() {
    mkdir -p "$CFG_DIR"

    # 确保 nftables 表和基础集合框架存在（与 mwan4 兼容）
    nft add table inet "$NFT_TABLE" 2>/dev/null || true
}

# ── 输入验证 ────────────────────────────────────────────
validate_input() {
    case "$name" in
        *[!a-zA-Z0-9_-]*|"")
            echo "无效的名称"
            exit 1
            ;;
    esac

    [ -n "$url" ] && case "$url" in
        http://*|https://*) ;;
        *) echo "无效的URL"; exit 1 ;;
    esac

    [ "$type" = 4 -o "$type" = 6 ] || { echo "无效的类型"; exit 1; }
}

# ── 下载 ────────────────────────────────────────────────
download_file() {
    tgt=$1
    src=$2
    retries=3
    count=0

    while [ $count -lt $retries ]; do
        wget -qO "$tgt" "$src" && [ -s "$tgt" ] && return 0
        count=$((count + 1))
        sleep 1
    done
    return 1
}

# ── 过滤 ────────────────────────────────────────────────
filter_file() {
    f=$1
    # 删除空行和包含非法字符的行
    sed -i -e '/^[[:space:]]*$/d' -e '/[^0-9a-fA-F:.\/]/d' "$f"
}

# ── 获取 nftables 地址族 ───────────────────────────────
nft_family() {
    [ "$1" -eq 6 ] && echo "ipv6_addr" || echo "ipv4_addr"
}

# ── 创建空集合（如果不存在）────────────────────────────
ensure_set() {
    name=$1
    type=$2
    fam=$(nft_family "$type")

    # 如果集合不存在则创建
    nft add set inet "$NFT_TABLE" "${NFT_PREFIX}_${name}" \
        "{ type $fam; flags interval; auto-merge; }" 2>/dev/null || true
}

# ── 原子更新集合 ───────────────────────────────────────
# 用 nft -f 的事务能力实现原子替换，比 ipset swap 更干净
update_nftset_atomic() {
    name=$1
    data_file=$2
    type=$3
    tmpfile="/tmp/nftset_${name}.nft"

    # 先确保集合存在
    ensure_set "$name" "$type"

    # 生成 nftables 事务文件（集合已由 ensure_set 创建，只操作元素）
    {
        echo "flush set inet $NFT_TABLE ${NFT_PREFIX}_${name}"

        if [ -s "$data_file" ]; then
            # 每行一个 CIDR，拼成 nftables 格式
            elements=""
            while IFS= read -r line; do
                [ -z "$line" ] && continue
                [ -z "$elements" ] && elements="$line" || elements="${elements}, ${line}"
            done < "$data_file"
            echo "add element inet $NFT_TABLE ${NFT_PREFIX}_${name} { $elements }"
        fi
    } > "$tmpfile"

    # 原子提交
    nft -f "$tmpfile"
    local rc=$?
    rm -f "$tmpfile"
    return $rc
}

# ── 添加集合 ────────────────────────────────────────────
add_nftset() {
    validate_input
    f="$CFG_DIR/${name}.txt"
    rm -f "$f"

    if ! download_file "$f" "$url"; then
        echo "下载失败或文件为空"
        rm -f "$f"
        exit 1
    fi

    filter_file "$f"
    if [ ! -s "$f" ]; then
        echo "文件内容无效（为空或包含非法字符）"
        rm -f "$f"
        exit 1
    fi

    if update_nftset_atomic "$name" "$f" "$type"; then
        # 记录配置到列表文件
        grep -v "^$name " "$CFG_DIR/nftset_list" > /tmp/nftset_list 2>/dev/null || true
        mv /tmp/nftset_list "$CFG_DIR/nftset_list" 2>/dev/null || true
        echo "$name $url $type" >> "$CFG_DIR/nftset_list"
    else
        exit 1
    fi
}

# ── 更新已有集合 ────────────────────────────────────────
clear_and_update_nftset() {
    f="$CFG_DIR/${name}.txt"
    : > "$f"

    info=$(grep "^$name " "$CFG_DIR/nftset_list")
    if [ -z "$info" ]; then
        echo "未找到配置: $name"
        exit 1
    fi

    url=$(echo "$info" | awk '{print $2}')
    type=$(echo "$info" | awk '{print $3}')

    if ! download_file "$f" "$url"; then
        echo "下载失败或文件为空"
        rm -f "$f"
        exit 1
    fi

    filter_file "$f"
    if [ ! -s "$f" ]; then
        echo "文件内容无效（为空或包含非法字符）"
        rm -f "$f"
        exit 1
    fi

    update_nftset_atomic "$name" "$f" "$type"
}

# ── 与 nftables 规则集成 ──────────────────────────────
# 在 nftables 规则中引用这些集合：
#   nft add rule inet fw4 mwan4_rules_ipv4 \
#       ip daddr @myset_myblocklist meta mark set 0x3f00
#
# 或直接查看集合内容：
show_nftset() {
    name=$1
    if [ -z "$name" ]; then
        nft list sets inet "$NFT_TABLE"
    else
        nft list set inet "$NFT_TABLE" "${NFT_PREFIX}_${name}"
    fi
}

# ── 删除集合 ────────────────────────────────────────────
delete_nftset() {
    name=$1
    nft delete set inet "$NFT_TABLE" "${NFT_PREFIX}_${name}" 2>/dev/null || true
    grep -v "^$name " "$CFG_DIR/nftset_list" > /tmp/nftset_list 2>/dev/null || true
    mv /tmp/nftset_list "$CFG_DIR/nftset_list" 2>/dev/null || true
    rm -f "$CFG_DIR/${name}.txt"
}

# ── 持久化（开机恢复）─────────────────────────────────
# nftables 不像 ipset 需要 save/restore，
# 只要把规则写入 /etc/nftables.d/ 即可自动加载
persist_all() {
    output="/etc/nftables.d/99-mynftsets.nft"
    mkdir -p /etc/nftables.d

    {
        echo "# Auto-generated by nftset manager"
        echo "table inet $NFT_TABLE {"

        while IFS= read -r line; do
            [ -z "$line" ] && continue
            name=$(echo "$line" | awk '{print $1}')
            type=$(echo "$line" | awk '{print $3}')
            data_file="$CFG_DIR/${name}.txt"
            fam=$(nft_family "$type")

            echo "    set ${NFT_PREFIX}_${name} {"
            echo "        type $fam"
            echo "        flags interval"
            echo "        auto-merge"

            if [ -s "$data_file" ]; then
                echo "        elements = {"
                while IFS= read -r cidr; do
                    [ -n "$cidr" ] && echo "            $cidr,"
                done < "$data_file"
                echo "        }"
            fi

            echo "    }"
        done < "$CFG_DIR/nftset_list"

        echo "}"
    } > "$output"

    # 持久化到文件，供 fw4 reload / 开机时自动加载
    # （/etc/nftables.d/ 下的文件会被 fw4 自动 include）
}

# ── 主入口 ──────────────────────────────────────────────
init_nftsets

case "${1:-help}" in
    add|update)
        name=$2; url=$3; type=$4
        [ "$1" = "add" ] && add_nftset || clear_and_update_nftset
        ;;
    delete|remove)
        delete_nftset "$2"
        ;;
    list|show)
        show_nftset "$2"
        ;;
    persist|save)
        persist_all
        ;;
    *)
        echo "用法: $0 {add|update|delete|list|persist} [参数...]"
        echo ""
        echo "  add <名称> <URL> <4|6>    下载并创建 nftset"
        echo "  update <名称>             重新下载并更新已有 nftset"
        echo "  delete <名称>             删除 nftset"
        echo "  list [名称]               查看 nftset 内容"
        echo "  persist                   将所有 nftset 持久化到 /etc/nftables.d/"
        ;;
esac
